### ISSUE TITLE
Fatal error: Uncaught TypeError: Cannot assign bool to property DCarbone\PHPFHIR\Config::$classesPath of type string

### ISSUE THREAD

**Issue by Aravind-MJ** [dcarbone/php-fhir#124]
In latest version, when installed as library and try to create config object, this error show. The origin of this error is from **constants.php** file where **PHPFHIR_DEFAULT_OUTPUT_DIR** is being set to false because input and output folders are not present when installed using composer. In the branch I can see that the folders exists and they have .gitignore files in them but they are not being created for the latest released version 3.0.3.

**Comment by dcarbone** [comment]
Yep, will address this asap.

**Comment by dcarbone** [comment]
@Aravind-MJ I have released v3.0.4, which removes the default value for this property in the config class.  Apologies for this ridiculous error!

Please try v3.0.4 and let me know if this resolves it for you!

**Comment by Aravind-MJ** [comment]
@dcarbone Thanks for the prompt response. Yes this resolves the error. Thank you!
