### ISSUE TITLE
PHPFHIRConfigKeyEnum::values() returning no results, thus setting PHPFHIRConfig doesn't work at all

### ISSUE THREAD

**Issue by yunosh** [dcarbone/php-fhir#128]
This is because the UnitEnum::cases() method returns a list of enums, not a list of descriptive array (see https://www.php.net/manual/en/unitenum.cases)

You cannot use this: https://github.com/dcarbone/php-fhir/blame/fdfdfc85f87bf2cb92e3931a7929f7bdc4edf8e0/template/core/enums/enum_config_key.php#L72

**Comment by dcarbone** [comment]
Very true!  I am on mobile at the moment, but when I get back in front of a desktop, I will update it as follows: 


```php
    public static function values(): array
    {
        $out = [];
        foreach (self::cases() as $k) {
             $out[] = $k->value;
        }
        return $out;
    }
```

**Comment by yunosh** [comment]
See also PR #129

**Comment by dcarbone** [comment]
@yunosh I've release v3.0.6 with a fix for this, as well as a test to help ensure it doesn't break in the future.

Could you test v3.0.6 output and let me know if this addresses it for you?

**Comment by yunosh** [comment]
Yes, this works for me now, but see my other comment in the PR about a BC break (that doesn't affect me personally though).
