### ISSUE TITLE
 'UnexpectedValueException' with message 'Value 'Quantity' is not part of the enum 

### ISSUE THREAD

**Issue by asc-net** [dcarbone/php-fhir#14]
After installing package and try your example I got : 

```
require __DIR__.'/vendor/autoload.php';
$xsdPath = 'xsd/';
$generator = new \DCarbone\PHPFHIR\ClassGenerator\Generator($xsdPath);
$generator->generate();
```

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'Value 'Quantity' is not part of the enum DCarbone\PHPFHIR\ClassGenerator\Enum\BaseObjectTypeEnum'

**Comment by dcarbone** [comment]
What version of the XSD's were you using?  I am able to run the generator against DSTU1, DSTU2, and STU3 codegen files.

**Comment by asc-net** [comment]
I am not sure what is the version, I used XSD folder attached to your package ,
to be precise, I attached this comment with folder I tried to use in the code

[xsd.zip](https://github.com/dcarbone/php-fhir/files/391445/xsd.zip)

**Comment by dcarbone** [comment]
I do not provide any xsd's, but it looks like this is a bleeding-edge release.  I currently only focus support on "official" releases (as of this moment they are: 0.0.82, 1.0.2, 1.4.0.  You are using 1.5.0), but I will begin work on compatibility for this new version as well.

**Comment by dataground** [comment]
STU3 will be released soon, i also need the support. I have fixed this bug. Please see my pull request #19

**Comment by dataground** [comment]
I have tested it with these versions:

Current stable versions:
http://hl7.org/fhir/DSTU1/fhir-all-xsd.zip
http://hl7.org/fhir/DSTU2/fhir-all-xsd.zip

STU3 (release candidate & nightly build)
http://hl7.org/fhir/2016Sep/fhir-all-xsd.zip
http://build.fhir.org/fhir-all-xsd.zip
