### ISSUE TITLE
Collection type fields are not being properly JSON serialized

### ISSUE THREAD

**Issue by Aravind-MJ** [dcarbone/php-fhir#140]
In `Questionnaire`, we have list of `items`. When calling `->jsonSerialize` on `Questionnaire`, it returns a `\stdClass` object but the values in `item` field is an array of `QuestionnaireItem` instances. Shouldn't they also be **_jsonSerialized_**? For now I have a helper function `nestedJsonSerialize` that I use for JSON encoding. Not sure about XMLSerialize though.

**Comment by dcarbone** [comment]
No. In PHP, that method is the implementation of the [JsonSerializable](https://www.php.net/manual/en/class.jsonserializable.php) interface and is intended to collect the fields to be encoded when passing the object to [json_encode](https://www.php.net/manual/en/function.json-encode.php).

To perform the actual serialization, use [json_encode](https://www.php.net/manual/en/function.json-encode.php).

**Comment by Aravind-MJ** [comment]
Ah so I don't have to call that function before passing the object into the `json_encode`. I understood that wrong. Gotcha.
