### ISSUE TITLE
base64Binary validation uses incorrect validation

### ISSUE THREAD

**Issue by yunosh** [dcarbone/php-fhir#147]
https://github.com/dcarbone/php-fhir-generated/blob/2e77abe0416ddb0c37ded6edee3295aa71e1c096/src/DCarbone/PHPFHIRGenerated/R4/FHIRElement/FHIRBase64Binary.php#L99 uses the following regular expression for validating base64Binary values: `'/^(\\s*([0-9a-zA-Z\\+\\/=]){4}\\s*)+$/'`
But according to https://hl7.org/fhir/datatypes.html#base64Binary the correct regex would be: `(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?`
Don't mind the different escaping and quoting.

**Comment by yunosh** [comment]
Ah well, then you at least use the correct regex for R4. Looks like the data provider in question needs to provide base64 chunks of 4 if they claim to use R4 then.

**Comment by dcarbone** [comment]
Base64 always produces output in chunks of 4, anyway.  This section on the trailing `=` on some base64-encoded values provides a good overview of why: https://en.wikipedia.org/wiki/Base64#Output_padding

**Comment by dcarbone** [comment]
Closing as this pattern is extracted from the actual XSD files and not defined by me.

See [R4](https://github.com/dcarbone/php-fhir-generated/blob/2e77abe0416ddb0c37ded6edee3295aa71e1c096/src/DCarbone/PHPFHIRGenerated/R4/FHIRBase64BinaryPrimitive.php#L89) and [R5](https://github.com/dcarbone/php-fhir-generated/blob/2e77abe0416ddb0c37ded6edee3295aa71e1c096/src/DCarbone/PHPFHIRGenerated/R5/FHIRBase64BinaryPrimitive.php#L109) generated code.
