### ISSUE TITLE
Not able to access classes

### ISSUE THREAD

**Issue by chandanwadhwa30** [dcarbone/php-fhir#148]
How I have installed on windows machine-
execute - composer require dcarbone/php-fhir
unzip directory -"fhir-spec" into c:\xampp\htdoc

Add below code into PHP file-
require_once 'vendor/autoload.php';
use DCarbone\PHPFHIRGenerated\R4\FHIRResource\FHIRDomainResource\FHIRBundle;

$bundle = new FHIRBundle();

not able to find class FHIRBundle()

Please help where i am wrong.

**Comment by jonathanchagas** [comment]
please post your composer.json and full path

**Comment by chandanwadhwa30** [comment]
[composer.json](https://github.com/user-attachments/files/18032703/composer.json)

For now implementation is on local machine so i am sharing directory structure-
![image](https://github.com/user-attachments/assets/fbf0f6ce-8de7-4f2f-9726-27dfd6b83cb6)
File name - "GenerateFHIRData.php" is for accessing libraries.  
class not found -FHIRBundle
some testing code inside this file-
<?php 
require_once 'vendor/autoload.php';
use DCarbone\PHPFHIRGenerated\R5\FHIRResource\FHIRBundle;

class FHIRModule {
    
    function createBundle()
    {
$bundle = new FHIRBundle();
    }
}


$config = new \DCarbone\PHPFHIR\Config(require 'config.php');

// next, iterate through all configured versions and render code:
foreach ($config->getVersions() as $versionConfig) {
    $versionConfig->getDefinition()->getBuilder()->render();
}
?>

**Comment by chandanwadhwa30** [comment]
Updated composer.json file
[composer.json](https://github.com/user-attachments/files/18047862/composer.json)

Please suggest

**Comment by dcarbone** [comment]
Your require statement expects you to have a file named `config.php` in your working directory, and that it returns a php associative array containing valid php-fhir config. 

In your case, it would be easier to simply define the config array in code, and pass it to the Config class constructor.

**Comment by dcarbone** [comment]
Well, this library just generates classes. From there, you interact with them like you would any other class. 

So, if you want to construct a resource you'd just call:

```
new ResourceClassName();
```

At that point, you can either define the fields and values in an associative array parameter to the constructor, or through the setter funcs on the class object. 

I've never looked at nrces resources before, but if they define their specs correctly you can rely on the very page you linked as to what fields are defined.

**Comment by chandanwadhwa30** [comment]
Is there any FHIR format validation classes in this or somewhere else.

**Comment by dcarbone** [comment]
What do you mean by format validation?  Are you running into an parsing issue?

There is also the FHIR validator tool, which might be what you're wanting: https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator

**Comment by chandanwadhwa30** [comment]
After creating FHIR data validation is defined as a process in ABDM eco system as a standard.

**Comment by dcarbone** [comment]
FHIR is represented as JSON or XML, both of which have well-defined schemas.  It is not the purpose of this tool to validate input JSON or XML, as the input must inherently be valid to be parsed.

The XML and JSON output by this library is inherently valid XML and JSON by virtue of the tooling used.

This library does provide tools to perform value validation.

Its unclear what you're asking for.

**Comment by chandanwadhwa30** [comment]
Getting following error when execution command -"./bin/generate.sh" in ubuntu machine

Generating classes for versions: DSTU1, DSTU2, STU3, R4

Downloading DSTU1 from http://hl7.org/fhir/DSTU1/fhir-all-xsd.zip
PHP Warning:  copy(http://hl7.org/fhir/DSTU1/fhir-all-xsd.zip): failed to open stream: HTTP request failed! HTTP/1.1 **403 Forbidden**
 in /__PATH__/php-fhir/bin/generate.php on line 395
**Unable to download.**

Below is the code in -generate.php on line 395

 if ($download) {
        echo 'Downloading ' . $version . ' from ' . $url . PHP_EOL;
        // Download/extract ZIP file
        if (!copy($url, $zip_file_name)) {    -----------> line number 395
            echo "Unable to download.\n";
            exit(1);
        }
    }

**Comment by dcarbone** [comment]
Well, you're receiving a 403 forbidden. You may need to change your user agent string. It is set here: [generated.php line 422](https://github.com/dcarbone/php-fhir/blob/1acdedc9de001c66a227b9abd1350d6ad03fc786/bin/generate.php#L422). 

They block some user agents, so I may need to update it again. You may also be region blocked, I'm not sure what all different restrictions they apply. 

I would also recommend only configuring the versions you actually intend to use. As far as I'm aware, nobody actually uses DSTU1 anymore; are you sure you even need to generate code for it?

Finally, if you are only wanting to generate code for the base versions, you may as well just use the pre-generated versions available here: https://github.com/dcarbone/php-fhir-generated

**Comment by chandanwadhwa30** [comment]
After adding user agent DSTU1,DSTU2,STU3 classes are generated but there is error while generating R4 as below(I am using v2.x branch)

Generating "R4" into __ PATH __/php-fhir/output/HL7/FHIR/R4
PHP Fatal error:  Uncaught UnexpectedValueException: Value 'integer64' is not part of the enum DCarbone\PHPFHIR\Enum\PrimitiveTypeEnum in __ PATH __/php-fhir/vendor/myclabs/php-enum/src/Enum.php:66
Stack trace:
#0 __ PATH __/php-fhir/src/Definition/TypeDecorator.php(244): MyCLabs\Enum\Enum->__construct('integer64')
#1 __ PATH __/php-fhir/src/Definition.php(80): DCarbone\PHPFHIR\Definition\TypeDecorator::determinePrimitiveTypes(Object(DCarbone\PHPFHIR\Config\VersionConfig), Object(DCarbone\PHPFHIR\Definition\Types))
#2 __ PATH __/php-fhir/bin/generate.php(481): DCarbone\PHPFHIR\Definition->buildDefinition()
#3 {main}
  thrown in __ PATH __/php-fhir/vendor/myclabs/php-enum/src/Enum.php on line 66

**Do you recommend to use pre generated classes from** - https://github.com/dcarbone/php-fhir-generated

**Comment by dcarbone** [comment]
The `integer64` type was added in R4 v4.3.0, and described in the [version table](https://github.com/dcarbone/php-fhir?tab=readme-ov-file#version-table) the v2 series does not support this. 

You will need to use v3.

**Comment by chandanwadhwa30** [comment]
Actually i am using PHP version -7.2 and can't update PHP due to some challenges. That's why is clone v2.x branch which is giving error -PHP Fatal error: Uncaught UnexpectedValueException: Value 'integer64' is not part of the enum

Any way to make it compatible with PHP 7.2

**Comment by dcarbone** [comment]
No, php 7.2 has been eol since November of 2020 ([source](https://www.php.net/eol.php)), and therefore should no longer be used. 

I can see about adding integer64 support to v2, but beyond that I consider the v2 branch itself eol'd.

**Comment by chandanwadhwa30** [comment]
Grateful if you can add integer64 support in v2. Hopefully it will work then.
On the other side i am not able to access pre generated classes from - https://github.com/dcarbone/php-fhir-generated
like this- 
$composition = new PHPFHIRGenerated\R5\FHIRBase\FHIRResource\FHIRDomainResource\FHIRComposition();
$composition->setStatus(new PHPFHIRGenerated\R5\FHIRBase\FHIRElement\FHIRCode('final'));

Uncaught Error: Class "DCarbone\PHPFHIRGenerated\R5\FHIRBase\FHIRResource\FHIRDomainResource" not found

**Comment by dcarbone** [comment]
Are you using composer, the generated autoloader, or manually requiring the class files?

**Comment by chandanwadhwa30** [comment]
Manually required the classes

**Comment by dcarbone** [comment]
The FHIRBase class and namespace does not exist in R4. You are trying to use R5 resources with generated code for R4.

In R4, the composition resource is here: https://github.com/dcarbone/php-fhir-generated/blob/main/src/DCarbone/PHPFHIRGenerated/R4/FHIRResource/FHIRDomainResource/FHIRComposition.php

**Comment by chandanwadhwa30** [comment]
After updating namespaces as per R4 still classes are not accessible.
composer.json file - 
[composer.json](https://github.com/user-attachments/files/18229001/composer.json)

PHP code- 
$composition = new DCarbone\PHPFHIRGenerated\R4\FHIRResource\FHIRDomainResource\FHIRComposition();
Error- 
Uncaught Error: Class 'DCarbone\PHPFHIRGenerated\R4\FHIRResource\FHIRDomainResource\FHIRComposition' not found

**Comment by dcarbone** [comment]
I'd need more information as to what your environment is to be able to help you.  This is confirmed working:

## composer.json

```json
{
    "require": {
        "dcarbone/php-fhir-generated": "2.0.5"
    }
}
```

## test.php

```php
<?php declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

$composition = new DCarbone\PHPFHIRGenerated\R4\FHIRResource\FHIRDomainResource\FHIRComposition();

echo gettype($composition) . PHP_EOL;
echo get_class($composition) . PHP_EOL;
```

## execution

```bash
$ php test.php
object
DCarbone\PHPFHIRGenerated\R4\FHIRResource\FHIRDomainResource\FHIRComposition
```
The autoloading system is very simple, and hasn't changed in a very long time.  Furthermore, you've mentioned you are stuck on php 7.2 necessitating the use of php-fhir v2, yet your most recent post is attempting to use php-fhir v3.

If you're running into a particular issue, I need the following:

1. Your exact version of PHP.
2. Your exact composer.json file.
3. The entire script that is failing.

**Comment by chandanwadhwa30** [comment]
Specs as requested- 
Your exact version of PHP -  7.2
Your exact composer.json file - [composer.json](https://github.com/user-attachments/files/18240034/composer.json)
Your target FHIR version- compatible with current specs
The entire script that is failing - 

<?php  declare(strict_types=1);

use DCarbone\PHPFHIRGenerated\R4\FHIRResource\FHIRDomainResource;
$composition = new DCarbone\PHPFHIRGenerated\R4\FHIRResource\FHIRDomainResource\FHIRComposition();
//$composition->setStatus(new Dcarbone\PHPFHIRGenerated\R4\FHIRBase\FHIRElement\FHIRCode('final'));
//$composition->setId('composition-1234');
//$composition->setStatus('final');
//$composition->setTitle('Discharge Summary');
print_r($composition);

echo "End";
?>

What i feel i haven't include - require ->  __DIR__ . '/vendor/autoload.php'; 
because i didn't find vendor director in pre generated classes from - https://github.com/dcarbone/php-fhir-generated

**I just clone the pre generate classes code and update composer.json and add write PHP script** 
Let me know where i am wrong.

**Comment by dcarbone** [comment]
You are not using composer correctly.

You have two options when using the pre-generated classes:

# Option 1: Composer
1. Install composer
  * You can find instructions here: https://getcomposer.org/doc/00-intro.md#installation-linux-unix-macos
2. Create project-specific `composer.json` file.
  * The `composer.json` you provided is from my pre-generated library.  It is not to be used directly in a project, rather it is used by composer to determine _how to create an autoloader for the library_.
3. Execute `composer install` from the root of your project
  * ^^^^^^^ THIS is what creates the `vendor` directory.  There is nothing to vendor with the pre-generated codebase as it does not have any dependencies.
4. Add the aforementioned `require` command at the top of your script.

Basically:

When using the project as a composer dependency, you _do not check out the library repo directly_!  You simply create a `composer.json` file with an entry in the `require` map for `dcarbone/php-fhir-generated`, and then execute `composer install`.

You can use the `composer.json` file I provide here as your starting point: https://github.com/dcarbone/php-fhir/issues/148#issuecomment-2560669997

Once you've created the correct `composer.json` file, you need to execute `composer install` so it will generate the vendor directory.  At that point, you'll need to add the `require` statement at the top, and the rest of your code will work.

# Option 2: Generated Autoloader

If you want to use the pre-generated classes _without_ composer, then you simply need to `require` the pre-generated autoloader:

Using tag v2.0.5:

```php
<?php

require __DIR__ . '/src/DCarbone/PHPFHIRGenerated/R4/PHPFHIRAutoloader.php';

DCarbone\PHPFHIRGenerated\R4\PHPFHIRAutoloader::register();

$composition = new DCarbone\PHPFHIRGenerated\R4\FHIRResource\FHIRDomainResource\FHIRComposition();

echo gettype($composition) . PHP_EOL;
echo get_class($composition) . PHP_EOL;
```

Executing the above script:

```bash
$ php test.php
object
DCarbone\PHPFHIRGenerated\R4\FHIRResource\FHIRDomainResource\FHIRComposition
```

# Conclusion

You will need to do one of the following, as has been mentioned by others in this thread:

1. Use composer properly, creating a new project and `composer.json` file and executing `composer install`
2. Use the pre-generated autoloader.

**Comment by chandanwadhwa30** [comment]
Tried with Option 2: Generated Autoloader
In Windows OS Classes are accessing pretty well 
In case of Linux(ubuntu) it is throwing error- 
PHP Parse error:  syntax error, unexpected 'bool' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /src/DCarbone/PHPFHIRGenerated/R4/PHPFHIRAutoloader.php on line 1272

code -
```
<?php

require  '/var/www/html/ss_telemed/api/fhirdata/src/DCarbone/PHPFHIRGenerated/R4/PHPFHIRAutoloader.php';
//require  '../src/DCarbone/PHPFHIRGenerated/R4/PHPFHIRAutoloader.php';
DCarbone\PHPFHIRGenerated\R4\PHPFHIRAutoloader::register();
$composition = new DCarbone\PHPFHIRGenerated\R4\FHIRResource\FHIRDomainResource\FHIRComposition();
print_r($composition);
?>
```

**Comment by dcarbone** [comment]
I use Linux as my primary OS, and the tests I posted earlier were all done on a Linux OS.

There is no significant difference between Linux and Windows PHP for this library.

More than likely you are running PHP5 on your Linux machine.

**Comment by chandanwadhwa30** [comment]
Now it's working with v2.05 classes. 
Cheers !!

**Comment by dcarbone** [comment]
Cool, happy to help!
