### ISSUE TITLE
SimpleQuantity serialising twice

### ISSUE THREAD

**Issue by garywarner** [dcarbone/php-fhir#20]
I've been using the Generator very successfully against DSTU-2 (from https://www.hl7.org/fhir/fhir-all-xsd.zip on 22-Feb-2016). I've grabbed the sample Immunisation xml from https://www.hl7.org/fhir/immunization-example.xml.html. It parses in beautifully. However, taking that parsed object (which only contains one SimpleQuantity under doseQuantity) and using xmlSerialise() to do a unit test produces:
```
	<doseQuantity>
		<value value="5" />
		<system value="http://unitsofmeasure.org" />
		<code value="mg" />
		<value value="5" />
		<system value="http://unitsofmeasure.org" />
		<code value="mg" />
	</doseQuantity>
```
where the SimpleQuantity is serialised out twice. I think I've tracked this down to the ```parent::xmlSerialize(true, $sxe);``` in FHIR\DSTU2\SimpleQuantity.php (which is in my root directory for this) - remove that line and you just get one set of quantities.

It seems odd that the classes Age, Count, Distance, Duration, etc together with SimpleQuantity should be in the root rather than under FHIRElement in the generated PSR4 tree? The .xsd has SimpleQuantity with base="Quantity" if that helps

Currently, I've just commented out the parent::xmlSerialize in my source, but thought I should flag this as an potential issue.

**Comment by dcarbone** [comment]
Well that's annoying, now isn't it.  As for their location...I genuinely don't remember why I did that :P

Thanks for the bug report, I'll get it resolved this weekend.

**Comment by dcarbone** [comment]
@garywarner I have checked in some changes that will hopefully solve and prevent this issue going forwards, and all `Quantity` classes are now under their own namespace under `Element`.

Let me know if this works for you!

**Comment by garywarner** [comment]
@dcarbone Worked first time - thank you
