### ISSUE TITLE
JSON serialization is implemented incorrectly

### ISSUE THREAD

**Issue by mikesoule** [dcarbone/php-fhir#25]
Hi,

Great library, thank you for open sourcing it!

I found a bug when serializing FHIR objects to JSON. Serializing the Patient.json example from the FHIR website will produce the output below, where quotes and whitespace a escaped multiple times.

The reason is because several of the jsonSerialize() methods are returning serialized JSON via json_encode(). The method jsonSerialize() should actually just return basic PHP types (string, integer, float, array, or object) which are then serialized recursively at the top-level json_encode() call.

It's an easy fix, would you like me to fix it and issue a pull request? We will need to regenerate dcarbone/php-fhir-generated as well after this repo is patched.

Example:
`{"id":"\"example\"","resourceType":"Patient","text":"{\"status\":\"\\\"generated\\\"\",\"div\":\"<div xmlns=\\\"http:\\\/\\\/www.w3.org\\\/1999\\\/xhtml\\\">\\n\\t\\t\\t<table>\\n\\t\\t\\t\\t<tbody>\\n\\t\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t\\t<td>Name<\\\/td>\\n\\t\\t\\t\\t\\t\\t<td>Peter James \\n              <b>Chalmers<\\\/b> (&quot;Jim&quot;)\\n            <\\\/td>\\n\\t\\t\\t\\t\\t<\\\/tr>\\n\\t\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t\\t<td>Address<\\\/td>\\n\\t\\t\\t\\t\\t\\t<td>534 Erewhon, Pleasantville, Vic, 3999<\\\/td>\\n\\t\\t\\t\\t\\t<\\\/tr>\\n\\t\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t\\t<td>Contacts<\\\/td>\\n\\t\\t\\t\\t\\t\\t<td>Home: unknown. Work: (03) 5555 6473<\\\/td>\\n\\t\\t\\t\\t\\t<\\\/tr>\\n\\t\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t\\t<td>Id<\\\/td>\\n\\t\\t\\t\\t\\t\\t<td>MRN: 12345 (Acme Healthcare)<\\\/td>\\n\\t\\t\\t\\t\\t<\\\/tr>\\n\\t\\t\\t\\t<\\\/tbody>\\n\\t\\t\\t<\\\/table>\\n\\t\\t<\\\/div>\"}","identifier":["{\"use\":\"\\\"usual\\\"\",\"type\":\"{\\\"coding\\\":[\\\"{\\\\\\\"system\\\\\\\":\\\\\\\"\\\\\\\\\\\\\\\"http:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/hl7.org\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/fhir\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/v2\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/0203\\\\\\\\\\\\\\\"\\\\\\\",\\\\\\\"code\\\\\\\":\\\\\\\"\\\\\\\\\\\\\\\"MR\\\\\\\\\\\\\\\"\\\\\\\"}\\\"]}\",\"system\":\"\\\"urn:oid:1.2.36.146.595.217.0.1\\\"\",\"value\":\"\\\"12345\\\"\",\"period\":\"{\\\"start\\\":\\\"\\\\\\\"2001-05-06\\\\\\\"\\\"}\",\"assigner\":\"{\\\"display\\\":\\\"\\\\\\\"Acme Healthcare\\\\\\\"\\\"}\"}"],"active":"true","name":["{\"use\":\"\\\"official\\\"\",\"family\":\"\\\"Chalmers\\\"\",\"given\":[\"\\\"Peter\\\"\",\"\\\"James\\\"\"]}","{\"use\":\"\\\"usual\\\"\",\"given\":[\"\\\"Jim\\\"\"]}","{\"use\":\"\\\"maiden\\\"\",\"family\":\"\\\"Windsor\\\"\",\"given\":[\"\\\"Peter\\\"\",\"\\\"James\\\"\"],\"period\":\"{\\\"end\\\":\\\"\\\\\\\"2002\\\\\\\"\\\"}\"}"],"telecom":["{\"use\":\"\\\"home\\\"\"}","{\"system\":\"\\\"phone\\\"\",\"value\":\"\\\"(03) 5555 6473\\\"\",\"use\":\"\\\"work\\\"\",\"rank\":\"1\"}","{\"system\":\"\\\"phone\\\"\",\"value\":\"\\\"(03) 3410 5613\\\"\",\"use\":\"\\\"mobile\\\"\",\"rank\":\"2\"}","{\"system\":\"\\\"phone\\\"\",\"value\":\"\\\"(03) 5555 8834\\\"\",\"use\":\"\\\"old\\\"\",\"period\":\"{\\\"end\\\":\\\"\\\\\\\"2014\\\\\\\"\\\"}\"}"],"gender":"\"male\"","birthDate":"\"1974-12-25\"","deceasedBoolean":"false","address":["{\"use\":\"\\\"home\\\"\",\"type\":\"\\\"both\\\"\",\"text\":\"\\\"534 Erewhon St PeasantVille, Rainbow, Vic  3999\\\"\",\"line\":[\"\\\"534 Erewhon St\\\"\"],\"city\":\"\\\"PleasantVille\\\"\",\"district\":\"\\\"Rainbow\\\"\",\"state\":\"\\\"Vic\\\"\",\"postalCode\":\"\\\"3999\\\"\",\"period\":\"{\\\"start\\\":\\\"\\\\\\\"1974-12-25\\\\\\\"\\\"}\"}"],"contact":["{\"relationship\":[\"{\\\"coding\\\":[\\\"{\\\\\\\"system\\\\\\\":\\\\\\\"\\\\\\\\\\\\\\\"http:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/hl7.org\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/fhir\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/v2\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/0131\\\\\\\\\\\\\\\"\\\\\\\",\\\\\\\"code\\\\\\\":\\\\\\\"\\\\\\\\\\\\\\\"N\\\\\\\\\\\\\\\"\\\\\\\"}\\\"]}\"],\"name\":\"{\\\"family\\\":\\\"\\\\\\\"du March\\\\\\\\u00e9\\\\\\\"\\\",\\\"given\\\":[\\\"\\\\\\\"B\\\\\\\\u00e9n\\\\\\\\u00e9dicte\\\\\\\"\\\"]}\",\"telecom\":[\"{\\\"system\\\":\\\"\\\\\\\"phone\\\\\\\"\\\",\\\"value\\\":\\\"\\\\\\\"+33 (237) 998327\\\\\\\"\\\"}\"],\"address\":\"{\\\"use\\\":\\\"\\\\\\\"home\\\\\\\"\\\",\\\"type\\\":\\\"\\\\\\\"both\\\\\\\"\\\",\\\"line\\\":[\\\"\\\\\\\"534 Erewhon St\\\\\\\"\\\"],\\\"city\\\":\\\"\\\\\\\"PleasantVille\\\\\\\"\\\",\\\"district\\\":\\\"\\\\\\\"Rainbow\\\\\\\"\\\",\\\"state\\\":\\\"\\\\\\\"Vic\\\\\\\"\\\",\\\"postalCode\\\":\\\"\\\\\\\"3999\\\\\\\"\\\",\\\"period\\\":\\\"{\\\\\\\"start\\\\\\\":\\\\\\\"\\\\\\\\\\\\\\\"1974-12-25\\\\\\\\\\\\\\\"\\\\\\\"}\\\"}\",\"gender\":\"\\\"female\\\"\",\"period\":\"{\\\"start\\\":\\\"\\\\\\\"2012\\\\\\\"\\\"}\"}"],"managingOrganization":"{\"reference\":\"\\\"Organization\\\\\\\/1\\\"\"}"}`

**Comment by dcarbone** [comment]
Thanks for the find!  Pretty silly oversight on my part. If you'd like, go ahead and make a PR and we'll go from there.

The current implementation was developed against 5.3.3, hence all the direct calls to jsonSerialize. Since the lib no longer targets 5.3, I would say just remove all direct calls to jsonSerialize.

**Comment by mikesoule** [comment]
Will do!

**Comment by dcarbone** [comment]
Also please excuse the code.  It is...old :P

**Comment by dcarbone** [comment]
@mikesoule Hey Mike, sorry it has taken me so long to get this issue sorted, but I have pushed a new version of this lib to master that, among other things, removes all of the nested calls to `json_encode`.

Let me know if this fixes the issue you're experiencing!

**Comment by mikesoule** [comment]
@dcarbone Actually, my apologies. I intended to contribute but just haven't had the time to do it. Thanks for the update!

**Comment by leonrenkema** [comment]
I have tried and works for me 👍

**Comment by dcarbone** [comment]
cool cool, is this one good to close?

**Comment by mikesoule** [comment]
@dcarbone I'd say yes. If i find another issue with JSON encoding, I can create a new issue or just reopen this one.
