### ISSUE TITLE
Idea to make the PHP code less verbose

### ISSUE THREAD

**Issue by leonrenkema** [dcarbone/php-fhir#26]
Not a bug but maybe a nice improvement.

I'm testing the generated code and writing some FHIR resources and the PHP code looks like this. There are a lot of elements that have one value or a fixed number of values.

```php
$p = new FHIRPatient();
$bool = new FHIRBoolean();
$bool->setValue('true');
$p->setActive($bool);

$gender = new \PHPFHIRGenerated\FHIRElement\FHIRAdministrativeGender();
$gender->setValue('male');
$p->setGender($gender);
```

Maybe it is an idea to introduce a __construct so the default values can be set while constructing the objects? With those the code could look like this, a lot shorter and no need for temporary variables. 

```php
$p = new FHIRPatient();
$p->setActive(new FHIRBoolean('true'));
$p->setGender(new FHIRAdministrativeGender('male'));
```

And maybe thinking ahead some FHIR concepts could be translated implicit from PHP native types to their FHIR equivalent. For example a boolean has only two valid values in FHIR, so the following code can be shortened:
```php
$bool = new FHIRBoolean();
$bool->setValue('true');
$p->setActive($bool);
```
to this with the same meaning: 
```php
$p->setActive(true);
```

**Comment by dcarbone** [comment]
This is an excellent idea.  I will begin working on this asap.

**Comment by leonrenkema** [comment]
Thanks for the quick response. If I can do anything please let me know.

**Comment by dcarbone** [comment]
@leonrenkema: i am still thinking this over in my head, I'm running into a few things:

h4. I am hesitant to subjectively implement constructors.  
Ideally, I would like to see a system where most / all of the logic present in the generated "Parser" class is moved into the constructors for each individual class.

To do this how I'd like, it would require 2 things:
1. Implement type-hinting on setter methods
2. Accept a single array as the argument for the constructor, requiring that the value of each parameter key is an instance of the appropriate object and use the setters to actually set the value on the parent object.

In an even more ideal world, I would like to bump the PHP req to 7.1 so I can take advantage of scalar type hinting, but I am willing to not for the moment.

h4. What about context-specific constructors?
One of my favorite concepts from Objective-C are the `with*` and `from*` constructor methods.  What would you say to something like the following:

```php
class FHIRResource {
    /** @var IDClass */
    private $id = null;

    public function __construct(array $data = []) {
        if (isset($data['id'])) {
            $this->setId($data['id']));
        }
    }

    public static function fromXML($xml) {
        $n = new static;
        // parse xml
        return $n;
    }

    public static function fromJSON($json) {
        $n = new static;
        // parse json
        return $n;
    }

    public function setId(IDClass $id) {
        $this->id = $id;
    } 
}
```

Granted, very stubby and bleh, but I think a world were an object is self-defining and self-constructing is ideal...

As an example, you could construct a `value` containing element like:

```php
$thing = new ThingElement(['inactive' => new BoolClass(['value' => true])]);
```

It is still a bit verbose, but will allow for `extension` and `id` to be set as well in the same statement, which I think is ideal.

Let me know if that would suffice for your workflow.

**Comment by leonrenkema** [comment]
My idea was to implement it for all datatypes that can be mapped to a PHP native type. When you want to use it for all resources that becomes somewhat more difficult. Also because a lot of values are optional.

I think your example would be great to implement. But I was thinking somewhat further to simplify the code some more.  
```php
$thing = new ThingElement(['inactive' => new BoolClass(['value' => true])]);
```
It would be nice if this can be something like this for places where xs:boolean is used, the same goes for xs:int, xs:string and all other simple types. (Maybe all FHIRElements that have only one value?) 
```php
$thing = new ThingElement(['inactive' => true]);
```

This would affect the setters and combined with the array from the __constructor this would work.
For example when the `setActive` in `FHIRPatient` will be something like this, that could save a lot of boilerplate code:
```php
public function setActive($active) {
      if (is_bool($active)) {
          $active = new FHIRBoolean(['value' => $active ? 'true': 'false']);
      }
      $this->active = $active;
      return $this;
}
```

**Comment by dcarbone** [comment]
Alrighty, I like the idea of making setters more intelligent.  As a part of this, I'd like to make the class vars private as well, thus forcing setter usage.  Would make it less confusing to use, I think...

**Comment by leonrenkema** [comment]
You can use `__set` to support using public attributes but still using the setters, but not everyone likes that kind of solutions because it involves magic methods.

Laravel's Eloquent uses it a lot and I must admit that I like that implementation because it makes the code very clean and readable.

But using setters also works for me, It makes it more explicit and type hinting and documentation on setters is much easier to support.

**Comment by dcarbone** [comment]
Ha, there will be zero magic getters and setters in this code.  They are slow and evil and should be avoided at all costs imo.

**Comment by leonrenkema** [comment]
Heheh, it is a "hot" topic with a lot of debate :) It depends a lot on the implementation if that is done right I think.

**Comment by dcarbone** [comment]
@leonrenkema: if you could, please try v1.0.0 of the generator (https://github.com/dcarbone/php-fhir-generated/releases/tag/v1.0.0 for the pre-generated version) and see if this addresses your concerns here.

**Comment by dcarbone** [comment]
Closing as I believe this to be resolved.
