### ISSUE TITLE
Parsing a Bundle resource

### ISSUE THREAD

**Issue by leonrenkema** [dcarbone/php-fhir#27]
I'm trying to parse and loop through this resource: [MedicationRequest](http://fhirtest.uhn.ca/baseDstu3/MedicationRequest?_include=*&_format=xml&_pretty=true) and I'm missing some method to determine the sort of resource that is included in the `FHIRResourceContainer`. 
Especially for included resources this is difficult because they can be of any type. 

```php
foreach ($object->entry as $entry) {
    if ($entry->getSearch()->getMode() == 'include') {
        $entry->getResource()->getPatient(); // type of included resource not known
    }
}
```

Maybe a method `$resource = FHIRResourceContainer->getResource()` should be added that returns the resource that is included and then `$resource instanceof FHIRPatient ` can be used to determine the type. Or something like $resource->getResourceName().

**Comment by dcarbone** [comment]
This is another good idea, one I've been tinkering with for awhile.  I will add this to the list.

Work is coming along on the other issues, just slowly :)

**Comment by leonrenkema** [comment]
Sure, no pressure :) 
I'm just dropping ideas while I'm using the library.

**Comment by dcarbone** [comment]
@leonrenkema: Sorry it has taken me so long to get to this!  Life has been hectic >_<

At any rate, I have added a new method to the `FHIRResourceContainer` class called `getResource()`.  It  just calls the `jsonSerialize()` internally, but I feel it is more idiomatic to call `getResource` rather than `jsonSerialize` :p

Let me know if this works for you!

**Comment by leonrenkema** [comment]
Thanks, It works!

Calling `jsonSerialize` internally doesnt matter to much, you can change it to a private method `getContainedResource` and let `jsonSerialize` and `getResource` call that one. But that are minor implementation details.

My intended code does now work as expected:
```php
$resource = $entry->getResource()->getResource();
if ($resource instanceof FHIRPatient) {
     // do stuff
}
```

**Comment by dcarbone** [comment]
Ha I actually don't really like repeated methods calls like that....what about condensing it to something like `$resource = $entry->getResource();` where every getter of a `FHIResourceBundle` inherently calls `getResource()` on the `ResourceBundle` class itself?  I think that would make for a cleaner usage experience...

**Comment by leonrenkema** [comment]
Sure, that would be better. I cant think of a case you want to use the FHIRResourceContainer. Calling getResource only once would also be more in line with the spec where a `<entry>` contains zero or one `<resource>` elements.

**Comment by dcarbone** [comment]
Cool cool, I'll get that implemented tonight.

**Comment by dcarbone** [comment]
alright, pushed a new version that updates all getters that return one or more ResourceContainers to now attempt to return the underlying object(s).

Let me know if this works for you.

**Comment by leonrenkema** [comment]
Great, it works 👍

**Comment by dcarbone** [comment]
excellent, thanks for helping test this.
