### ISSUE TITLE
URL appears as element instead of attribute

### ISSUE THREAD

**Issue by leonrenkema** [dcarbone/php-fhir#28]
I found a problem when using an extension. When I set the URL with `setUrl()` it is rendered as an XML element instead of an attribute on the extension element. 
```php
$assemblyOrder = new FHIRExtension();
$assemblyOrder->setUrl("http://hl7.org/fhir/StructureDefinition/humanname-assembly-order");
$valueCode = new FHIRCode();
$valueCode->setValue($this->getHumanNameAssemblyOrder($patientModel));
$assemblyOrder->setValueCode($valueCode);
$name->addExtension($assemblyOrder);
```
This gives the following XML:
```xml
<extension>
  <valueCode value="NL3"/>
  <url value="http://hl7.org/fhir/StructureDefinition/humanname-assembly-order"/>
</extension>
```
But should be this instead: 
```xml
<extension url="http://hl7.org/fhir/StructureDefinition/humanname-assembly-order">
  <valueCode value="NL3"/>
</extension>
```

**Comment by dcarbone** [comment]
Yeah this is an issue I wrestled with for awhile.  Since URL's can have extensions and Id's of their own, they cannot just always be attributes.  In the interest of saving time initially, I made the decision to always make them elements.

At some point in the near future I think it's reasonable to allow for more intelligent serialization where if there is an extension or id present, create an element, otherwise set as attribute on parent.

**Comment by leonrenkema** [comment]
I'm not sure if I understand you correctly. The URL in an extension is always rendered as an attribute, when an URI is added as value it is contained in `valueUri`.

When I change the lines in `FHIRExtension.php` to the following, it outputs correctly and URI can still be extended.
```php
if (isset($this->url)) {
      $sxe->addAttribute('url', (string) $this->url);
}
```

But maybe I'm missing something important here..

**Comment by leonrenkema** [comment]
Any news on this issue?

**Comment by dcarbone** [comment]
Unfortunately I've not had any time to devote to this lib recently, so no :\

The serialization and construction of objects is something I have in my personal backlog to improve, just need the spare time to do so.

**Comment by leonrenkema** [comment]
No problem, just curious. I have looked at it for a while but it is not a simple fix and I would have to figure out how it works 😅
For now I changed the generated code.

**Comment by leonrenkema** [comment]
sorry wrong button

**Comment by leonrenkema** [comment]
I want to ask if it is an idea to hotfix your generated source to fix this issue and we can load that repo?

**Comment by dcarbone** [comment]
i would rather not start creating hotfix branches in the generated repo, but i'll tell you what i will have some spare time with the holidays coming up later in this week.  I can spend some time figuring this issue out.

Off the top of my head, there are 2 potential big-gain solutions here:

1. Generate an interface per class in addition to concrete implementations, each var maps to the interface, allow specifying a map of `["ElementName" => "ClassName"]`.  This would be really powerful, and allow implementers to overload specific classes, altering whatever they want.
1. A `callbacks` system, whereby a `callable` can be executed for different phases of the generation / parsing.

I think, in general, option 1 is better.

This would also probably be useful:
1. Add config option for "simpleAsAttribute" or something.  If true, simple type elements that ONLY contain a value will be placed as an attribute on their parent element.

Also, yes, this code is pretty nasty.  i wrote it very quickly on the side and i personally only had to use it once before i found a new job.  I no longer directly work with FHIR at all :\

Anyway, let me know if you can wait until this weekend and I will get something implemented

**Comment by garywarner** [comment]
Was wrestling with this and the newer versions that use the Config object allow you to override:
```php
$objConfig->setXmlSerializationAttributeOverride('Extension', 'url');
```

or if you are setting with an array call to Config __constructor
```php
$objConfig = new \DCarbone\PHPFHIR\ClassGenerator\Config(array(
		'XsdPath' => $sXSDPath,
		'OutputNamespace' => $sNamespace,
		'OutputPath' => $sOutputPath,
		'XmlSerializationAttributeOverrides' => array(
				'Extension' => 'url',
		),
));
```

generates as an example:
```xml
<extension url="https://fhir.nhs.uk/STU3/StructureDefinition/Extension-CareSettingType-1">
```

@leonrenkema and @dcarbone you might consider this issue closed with this active "workaround"?

**Comment by dcarbone** [comment]
@garywarner We can, however I am keeping it open with the other feature requests to remind myself of what to implement in the new upcoming release i am working on in the `feature/refactor` branch.  I reckon I am roughly 2/3 completed with the rewrite into something much easier to use and contribute to by the community, and for me to maintain.

**Comment by garywarner** [comment]
@dcarbone Just big thanks for keeping up the sterling work

**Comment by dcarbone** [comment]
@garywarner & @leonrenkema: I had originally targeted this as part of the v1.0 release, but it appears i broke this while attempting to address something else.  sigh.  i will target this for v1.0.1

**Comment by dcarbone** [comment]
@garywarner & @leonrenkema: I have release v1.0.5 with the express intent of providing better support for this.  Could you give v1.0.5 a try and see if it behaves as you expect?

**Comment by leonrenkema** [comment]
Thanks for the updates!
When I test 1.0.5 I see an extra attribute in the XML output on several places. This is on several elements, FHIRIdentifier, FHIRQuantity.
```
 <quantity value="7">
    <value value="7"/>
  </quantity>
```
This is generated with a simple setQuantity(). 
In FHIRQuantity I see the following line code that is most likely the source of this extra attribute:
```
if (null !== ($v = $this->getValue())) {
      $sxe->addAttribute(self::FIELD_VALUE, (string)$v);
      $v->xmlSerialize($sxe->addChild(self::FIELD_VALUE, null, $v->_getFHIRXMLNamespace()));
}
```

**Comment by dcarbone** [comment]
@leonrenkema: i intentionally put it in both places just for simplicity's sake for the time being.  Is causing issues?  Also, have a go at the v2 release, quite a bit of improvements in there over the v1 releases.

**Comment by leonrenkema** [comment]
When I try 2.0.5 I see the same generated code, problem is that the generated XML is not according to spec.

When I check the following generated XML:
```
<?xml version="1.0"?>
<Quantity xmlns="http://hl7.org/fhir" value="2">
  <code value="245"/>
  <system value="urn:oid:2.16.840.1.113883.2.4.4.1.900.2"/>
  <unit value="STUK"/>
  <value value="2"/>
</Quantity>
```
I see the following validation errors. Also there are some errors about the order of the elements that are not according to the specs.
```
Internal error in location for message: 'Error in ?? at 1, 1: Found / expecting a token name', loc = '/f:Quantity', err = 'Undefined attribute '@value' on Quantity for type Quantity (properties = [Quantity.id, Quantity.extension, Quantity.value, Quantity.comparator, Quantity.unit, Quantity.system, Quantity.code])'
*FAILURE* validating resource.xml:  error:4 warn:0 info:0
  Error @ Quantity.system (line 4, col60) : As specified by profile http://hl7.org/fhir/StructureDefinition/Quantity, Element 'system' is out of order
  Error @ Quantity.unit (line 5, col23) : As specified by profile http://hl7.org/fhir/StructureDefinition/Quantity, Element 'unit' is out of order
  Error @ Quantity.value (line 6, col21) : As specified by profile http://hl7.org/fhir/StructureDefinition/Quantity, Element 'value' is out of order
  Error @ /f:Quantity (line 2, col49) : Undefined attribute '@value' on Quantity for type Quantity (properties = [Quantity.id, Quantity.extension, Quantity.value, Quantity.comparator, Quantity.unit, Quantity.system, Quantity.code])
```

**Comment by dcarbone** [comment]
what are you using for your validation testing?  I'd like to add it to the phpunit tests.

element order would be...very tedious to implement.  is that something that is truly required?

**Comment by leonrenkema** [comment]
It is a Java jar file that you can download here, https://wiki.hl7.org/Using_the_FHIR_Validator. I think it would be difficult to implement in phpunit. But we can generate some validated examples and use that as comparison.

**Comment by dcarbone** [comment]
I had assumed it was a java utility based on the output. I would not re-implement it in php, more i would shell out to it and rest the return.

I'll have a look at it this weekend.
