### ISSUE TITLE
FHIRResourceContainer constructor

### ISSUE THREAD

**Issue by leonrenkema** [dcarbone/php-fhir#31]
Hi, 

When I generate the FHIR model from the latest code in master, I bump into a problem with the constructor of the FHIRResourceContainer. This is my test code: 

```php
use PHPFHIRGenerated\FHIRResourceContainer;
use PHPFHIRGenerated\FHIRDomainResource\FHIRMedicationRequest;

require 'vendor/autoload.php';

$container = new FHIRResourceContainer(new FHIRMedicationRequest());
```

When I try to run this I get the following error `Call to undefined method PHPFHIRGenerated\FHIRResourceContainer::set()`. It not clear to me how this is supposed to work, there seems to be a problem in this line of the FHIRResourceContainer, `$n = ltrim(strrchr(get_class($data)), "\FHIR");` PHPstorm complains that the required param for strrchr is missing. 

When I try it like this `$container = new FHIRResourceContainer(new FHIRMedicationRequest());` I get the same error but triggered on another line in the code.

**Comment by dcarbone** [comment]
Yup, oversight on my part.  I unfortunately have not had time to do much with this lib recently, but I did push what I hope will be a quick fix for you.  The constructor mechanism is still very much in-development, so I expect there to be other issues as well.

Thanks for letting me know about this one!
