### ISSUE TITLE
Double quotes when json_encode is used

### ISSUE THREAD

**Issue by mattkoch614** [dcarbone/php-fhir#32]
Thanks for the great library!

I'm attempting to create a simple Observation resource using FHIR 3.0.1. I generated all of the PHP classes from a downloaded set of XSD files with no issue using the instructions here. I'm running into a strange issue when I attempt to ``json_encode`` my object. See some sample code below:

```php
$observation = new FHIRObservation();
$id = new FhirId();
$id->setValue("1234");
$observation->setId($id);
$issued = new FHIRInstant();
$issued->setValue(Carbon::now()->toIso8601String());
$observation->setIssued($issued);
var_dump(json_encode($observation));
die();
```

This produces:

```
'{"id":"\"1234\"","resourceType":"Observation","issued":"\"2018-02-09T19:44:53+00:00\""}'
```

As you can see, it looks like the ``id`` and ``issued`` properties are being escaped, but the ``resourceType`` property is fine. Perhaps I'm missing something obvious - can anyone lend a hand?

**Comment by leonrenkema** [comment]
When I try to run your code in Laravel I see the following `{"id":"1234","resourceType":"Observation","issued":"2018-02-09T22:35:33+01:00"}` but I'm using pregenerated files from a fork (https://github.com/leonrenkema/php-fhir-generated/tree/develop) there is a little bugfix in there which is not fixed in the main library.

Maybe you can test that to see if the problem still exists then?

**Comment by mattkoch614** [comment]
Happy to give this a shot when I'm able. Any idea what the bug fix is? Seems like a good opportunity to open a PR here.

**Comment by dcarbone** [comment]
Yes, it is resolved in master.  I will create a bugfix version of 0.5 for those who are using a "stable" release.

I really should release 0.6 soon, i think lol...

**Comment by dcarbone** [comment]
@mattkoch614 sorry for that bug, I have created release 0.5.1 that addresses this issue.  Let me know if you find anything else!

**Comment by dcarbone** [comment]
oop, let me know if I can close this!

**Comment by mattkoch614** [comment]
Thanks for the quick response! Once I get a chance to test this I’ll report back.

**Comment by dcarbone** [comment]
@mattkoch614: any updates on whether I can close this ticket?

**Comment by mattkoch614** [comment]
@dcarbone All set - I updated my version to ``0.5.1`` and re-generated my classes. I then ran through the same scenario I originally reported and the double quote issue is now gone.

Thanks for the help!
