### ISSUE TITLE
test FHIR URL is down

### ISSUE THREAD

**Issue by wwwalker** [dcarbone/php-fhir#33]
http://fhir2.healthintersections.com.au/open/ is down.

**Comment by dcarbone** [comment]
So it is, and unfortunately appears as though Graham's other open servers are also not responding. In the meantime, you can try one of the other hosts here: http://wiki.hl7.org/index.php?title=Publicly_Available_FHIR_Servers_for_testing

**Comment by wwwalker** [comment]
May be replace the broken URL with your new one on the Code page.

**Comment by dcarbone** [comment]
Closing as this is no longer an issue.
