### ISSUE TITLE
Purpose of FHIRResourceContainer?

### ISSUE THREAD

**Issue by mgenereu** [dcarbone/php-fhir#34]
Why are resources wrapped in FHIRResourceContainer? It looks like it's an alternative approach for polymorphism.  I also can't tell what's in a FHIRResourceContainer since it doesn't track which field is holding the resource. I had to write a helper to extract resources by class. My gut's telling me I'm using this wrong but I'm not sure where to start.  Thank you for looking at this question!

**Comment by dcarbone** [comment]
I agree it can be annoying to use, however its primary reason for existence is simply that it is part of the spec.  Have a look [here](http://hl7.org/fhir/stu3/fhir-base.xsd) and search for `ResourceContainer`.

Given the special case that is this object, I have considered adding a configuration option that would allow a user to remove it from the object tree and just have it's contained object in its place.  If you want to take a stab at such an implementation, feel free to make a PR :)

In the meantime, you can just call the `jsonSerialize()` method on the ResourceContainer object to get the populated object, if there is one.  I really do NOT like this "solution", as it isn't one, but it will at least get you there without having to write your own extraction logic.
