### ISSUE TITLE
ResourceContainers may only contain 1 object, "0" values provided

### ISSUE THREAD

**Issue by LucidTaZ** [dcarbone/php-fhir#35]
I'm getting this error when trying to parse a resource with one contained resource. I believe there is a bug in how the ResourceContainer is constructed. The constructor expects one element in the parameter, but the parser constructs it with no parameters and then calls the setter separately.

Version used: the master branch of today, 2018-05-29. FHIR STU3.

For the sake of discussion, the constructor of `FHIRResourceContainer`:
```php
    public function __construct($data = [])
    {
        if (is_object($data)) {
            $this->{sprintf('set%s', substr(strrchr(get_class($data), 'FHIR'), 4))}($data);
        } else if (is_array($data)) {
            if (1 === ($cnt = count($data))) { // <-- always expects something in the parameter!
                $this->{sprintf('set%s', key($data))}($data);
            } else {
                throw new \InvalidArgumentException(sprintf('ResourceContainers may only contain 1 object, "%d" values provided', $cnt));
            }
        } else if (null !== $data) {
            throw new \InvalidArgumentException('$data expected to be object or array, saw '.gettype($data));
        }
    }
```

The caller is (in the case of JSON) `PHPFHIRResponseParser::_parseJsonObject()`:
```php
    private function _parseJsonObject($jsonEntry, $fhirElementName)
    {
        if ('html' === $fhirElementName) {
            return $jsonEntry;
        }

        if (false !== strpos($fhirElementName, '-primitive') || false !== strpos($fhirElementName, '-list')) {
            return $jsonEntry;
        }

        $map = $this->_tryGetMapEntry($fhirElementName);

        $fullClassName = $map['fullClassName'];
        $properties = $map['properties'];

        $object = new $fullClassName; // <-- passes no parameters!

        // ...
```

I fixed it in my case by only throwing the `InvalidArgumentException` if the count is greater than one, allowing the use case of zero arguments + calling a setter. But is this the correct way to fix this? If so, I can create a PR.

Another possible fix is to default the constructor parameter to `null` instead of an empty array.

**Comment by dcarbone** [comment]
@LucidTaZ: Yup, oversight on my part.  Thanks for reporting.  I've updated the generator to allow for empty input on construct.

Let me know if it works for you.

**Comment by dcarbone** [comment]
I agree, however time has not been permissive :)
