### ISSUE TITLE
FHIRBoolean::getValue() return type 

### ISSUE THREAD

**Issue by mgenereu** [dcarbone/php-fhir#36]
I think this might be under the TODO section as "Typecast scalar values in XML responses to proper PHP type". If that is the same concept, then I just need some direction to make a PR. I can't find what in this code base is generating that method in the generated class.

I'm using the generated STU3 with much success but my IDE noted that the FHIRBoolean.php file is claiming in the docblock to return a `string` for getValue and it actually returns a `boolean`. I would expect a boolean so how do I fix this?  I'm parsing a JSON file and maybe that makes a difference versus XML?

 https://github.com/dcarbone/php-fhir-generated/blob/STU3/src/PHPFHIRGenerated/FHIRElement/FHIRBoolean.php#L82

**Comment by dcarbone** [comment]
In XML all values are, by default, strings and I do no sort of unmarshalling type-casting when unmarshalling responses.  Being PHP, and having not implemented PHP 5 object and array type-hinting nor PHP 7 scalar type-hinting, the value can quite literally be whatever you want. It hinges upon you to set the correct type.

Ultimately, yes, I would like to implement type specificity throughout the generated code.

**Comment by mgenereu** [comment]
Okay. So it's set during import of the JSON to the correct type coincidentally. Perfect. Thank you so much for the clarity.
