### ISSUE TITLE
Config Constructor fails when XsdPath not provided

### ISSUE THREAD

**Issue by garywarner** [dcarbone/php-fhir#40]
Creating a Config object without passing an array with the XsdPath defined fails because the call to `setXsdPath()` in the constructor won't find the directory `null` that  it's passed when `$this->xsdPath` isn't set.

**Workaround**: Pass in the XsdPath in an initialisation array rather than using `setXsdPath()` after construction

**Comment by dcarbone** [comment]
@garywarner Is the new updated generator working for you?
