### ISSUE TITLE
Question to users:  How often do you use multiple versions in the same codebase?

### ISSUE THREAD

**Issue by dcarbone** [dcarbone/php-fhir#42]
As part of my refactor branch, I am working on improving the usability and efficiency of the generated code.  A piece of this is that I am now defining a suite of constants (viewable here: [constants.php](https://github.com/dcarbone/php-fhir-generated/blob/feature/refactor/src/DCarbone/PHPFHIRGenerated/constants.php)).  Due to limitations with older versions of PHP that I would still like to support, however, these are currently defined in the global namespace.

This would, of course, conflict if you expected to be able to generate code for multiple versions of FHIR.  This could be solved by wrapping constants in a container class, but I would like to avoid that if possible.

So the question i pose is:  how often do you use multiple versions in the same code base?

It would not be the end of the world to wrap this output in a namespaced `Constants` class or something, or even break it up into groups like `GenerationMetadata`, `FHIRTypes`, `FHIRClasses`, etc., and reference those instead.

I may go ahead and do this anyway, but I am curious how often this case is used in the wild.

**Comment by leonrenkema** [comment]
We only use one version, but maybe in the future we need to support multiple version because we connect with several other parties and systems.

**Comment by dcarbone** [comment]
I have gone ahead and just converted it to using public constants on an abstract class (https://github.com/dcarbone/php-fhir-generated/blob/feature/refactor/src/DCarbone/PHPFHIRGenerated/PHPFHIRConstants.php)
