### ISSUE TITLE
is FHIR free to get data?

### ISSUE THREAD

**Issue by yahyatabba** [dcarbone/php-fhir#43]
hello,

is FHiR free to get data from HL7?
how to use 'php-fhir' with my server? how can I prepare the server?

Thank you

**Comment by dcarbone** [comment]
@yahyatabba: apologies for the severely delayed reply:

FHIR is just a specification, it is entirely free to use.  If you're looking for test servers, a list of publicly available ones can be found here: https://wiki.hl7.org/Publicly_Available_FHIR_Servers_for_testing
