### ISSUE TITLE
Would it be helpful to create secondary repos containing the generated files for each FHIR version?

### ISSUE THREAD

**Issue by mmcev106** [dcarbone/php-fhir#47]
It seems like it'd be ideal to be able to add composer dependency containing the already generated files for a specific FHIR version.  I'm guessing there might be a reason this isn't the preferred solution that I haven't stumbled across yet.  I'm curious...

**Comment by dcarbone** [comment]
Hmm I'm not 100% sure what you mean there.  Do you mean adding them as a dependency to _this_ repo?  If so, this repo is not meant to be checked out to provide you with generated versions.  This is purely the generator itself.  Currently I have some pre-generated versions here: https://github.com/dcarbone/php-fhir-generated, but I have not been pushing versions there as often as I'd like as I'm still finishing up the refactored version of the generator itself.

Ideally I would like to have specific repos per release of FHIR that are automatically pushed to per successful build & test per latest generator commit.  I just haven't had time to set that up yet.

**Comment by mmcev106** [comment]
I knew I was missing something!  I hadn't come across the generated repo yet.  I'll send in a PR for R4 on Monday.
