### ISSUE TITLE
Access levels of fields in generated classes

### ISSUE THREAD

**Issue by shehi** [dcarbone/php-fhir#49]
This generator creates "private" fields for classes generated. Would it be possible to switch this to "protected", as it is impossible to extend the generated classes otherwise? Thanks.

**Comment by dcarbone** [comment]
Hmm, would it not be possible to use the getters & setters?  I don’t mind the switch, but I’m curious what the need is. Mind posting an example of what you’d like to do?

**Comment by shehi** [comment]
Of course. My use case is implementing FHIR concepts as Entities in Doctrine/Symfony, and in many cases, Symfony spits at you when it sees private fields. Having them as "protected" solves a lot of problems. Thanks.

**Comment by dcarbone** [comment]
@shehi: i've updated the classes to use `protected` instead of `private` and pushed the changes to master of `php-fhir-generated`.

If things look good, i'll create a v1.0.3 release to address this and #50.

**Comment by shehi** [comment]
Looks good. Thanks.
