### ISSUE TITLE
Error generating classes from xsd

### ISSUE THREAD

**Issue by 0xPr0xy** [dcarbone/php-fhir#5]
Hello,

I'm trying to use your library in my project, but unfortunately an exception is thrown while executing the generate method.

This is the stack trace I'm getting: [stacktrace](https://gist.github.com/0xPr0xy/3a389f3bf7a6df307d8b975bcba86790)

This is the code that calls the generate() method:

`$xsdDirectory = $this->getXsdDirectory();`
`$modelDirectory = $this->getModelDirectory();`
`$generator = new Generator($xsdDirectory, $modelDirectory, 'models');`
`$generator->generate();`

The XSD files I'm using are from FHIR DSTU1 version (0.0.82)
Downloaded from: http://hl7.org/fhir/directory.html

I hope you can help me find out why I'm getting this exception and how to resolve it.
Thanks in advance!

**Comment by dcarbone** [comment]
Hi,

I am really sorry it took me so long to get to this!  I just started a new job which has been taking up all of my time.  The majority of more recent development on this lib has been against 1.0.2, so I am not surprised I missed something in support of 0.0.82.

I will take a look at this tonight and hopefully get a fix for you soon.

**Comment by dcarbone** [comment]
Hey @0xPr0xy,

When you get a chance, could you test your implementation with the new 0.4.2 release?  I hope I have taken care of the issue.

If not, could you paste the error message itself into this issue?  It should contain the full XML of the element that failed to parse and will help me with debugging.

Thanks!

**Comment by 0xPr0xy** [comment]
@dcarbone Thanks! the 0.4.2 release resolved this issue, and elements nested in choice elements are now also generated correctly with the 0.8.2 version.

**Comment by dcarbone** [comment]
Good to hear, thanks!
