### ISSUE TITLE
Escape @ signs in DocBlocks

### ISSUE THREAD

**Issue by shehi** [dcarbone/php-fhir#50]
Hi again,

Having words starting with @ sign (e.g. @value , @id) in DocBlock is causing trouble with Symfony's annotation libraries. Symfony attempts to resolve them as valid annotation bits, requesting to provide classes for such resolution:

![image](https://user-images.githubusercontent.com/653569/67691415-d5e1ba00-f99e-11e9-8172-69bdbba03d2a.png)

If escaped (e.g. ```\@value```) this problem is fixed. I realize this might cause DocBlocks to look uglier. But nevertheless, I have to ask: Would it be possible to escape all @ signs in comments please? Thanks.

P.S.: This problem was actually raised here 2 years ago - https://github.com/doctrine/annotations/issues/169 but Doctrine team decided to bin it. And because of that, it's impossible to extend generated FHIR classes to be used as Doctrine entities.

**Comment by dcarbone** [comment]
Ah, that is annoying.  Ok, I'll get a fix pushed here in a bit.

**Comment by dcarbone** [comment]
@shehi: i've pushed the updated output to the master branch of php-fhir-generated, could you check out `dev-master` and see if its sufficiently escaped?

**Comment by shehi** [comment]
Works fine! Thanks.
