### ISSUE TITLE
[Note] Fields with default value of NULL

### ISSUE THREAD

**Issue by shehi** [dcarbone/php-fhir#51]
Hey @dcarbone ! First I wanted to thank for your quick support regarding #49 and #50 !

With this ticket I want to note that in PHP, you don't need to initiate class properties with NULL value, as it is already done by default when you declare those properties. So something like this is unnecessary:

```public $fieldName = null;```

Declaring already initializes them to a null value:

```public $fieldName;```

Thanks!

**Comment by dcarbone** [comment]
@shehi i'm aware of this, but I prefer things to be explicitly defined.  Unless there is a reason not to do so, I am going to close this issue.
