### ISSUE TITLE
Would it make sense to associate resources by reference?

### ISSUE THREAD

**Issue by mmcev106** [dcarbone/php-fhir#52]
In my current use case I'm building a **FHIRQuestionnaireResponse** that involves nesting a bunch of  **FHIRQuestionnaireResponseItem** instances.  Since **FHIRQuestionnaireResponseItem::addItem()** does not accept items by references, I am not able to modify an item after adding it to another item (or the parent response).  I think that means I'm going to have to do my data manipulation using nested arrays mimicking the **FHIRQuestionnaireResponse** structure I want, then do another loop to actually create the FHIR classes after the data is finalized.

There's no expectation at all for you to work on this @dcarbone.  I'm mainly just curious what you think of the idea.

**Comment by dcarbone** [comment]
@mmcev106 I'm not sure what you mean, objects are always passed by reference in PHP.  Are you wanting to re-define the reference?

See here for an example of what i mean: https://3v4l.org/rYmCg

Could you provide a small example of what you're running into?

**Comment by mmcev106** [comment]
Redacted.  As you might have expected, I was just doing something silly with references that it took me a while to find.  Closing...
