### ISSUE TITLE
Underscore properties (e.g. _xmlns) should be private

### ISSUE THREAD

**Issue by shehi** [dcarbone/php-fhir#55]
Hey @dcarbone ,

It's me again :) I have been extensively working with your FHIR libs - so before I start: THANK YOU  greatly for creating them. Keep up the awesome work! :heart: 

As you might remember from my earlier issues created, I have been implementing your libraries in Doctrine environment by extending them on my MongoDb-ODM document-classes. In past, we turned public properties into protected, which works VERY WELL. 

But I have one more request/suggestion: can we turn underscore properties (e.g. _xmlns and such) to private ones, so that they don't create noise in Doctrine ODM/ORM documents/entities? You actually already created few private properties there (like those for ongoing validation work you plan to implement in future). Because when they are accessible by ORM/ODM assets, resources (e.g. API Resources) using them mis-identify them as actual collection fields or table columns. These private properties can still be used in original FHIR classes of yours and in future, if need be, we can add public getters/setters for them.

What you think? Doable?

**Comment by dcarbone** [comment]
I agree. I originally had them private but made them protected for #49.  If these aren't wanted in models, I will make them private again.

**Comment by dcarbone** [comment]
@shehi: just pushed v2.0.3 with these changes. Let me know if you run into any other issues!
