### ISSUE TITLE
_fieldValidation property as protected

### ISSUE THREAD

**Issue by shehi** [dcarbone/php-fhir#57]
@dcarbone , hello!

If possible, let's have ```_fieldValidation``` field of code-primitive-list types with ```protected``` access please - currently, they are ```private```. Sample classes are almost all of them ending with ```List``` in their classnames (e.g. ```FHIRNameUseList```). Last time we discussed the topic of validation, you said it might take some time until you finalize it. So I am attempting to create my basic validation processes for now (mostly trait based) and for that reason, need an access to the aforementioned property (```_fieldValidation```). Thanks!

**Comment by dcarbone** [comment]
@shehi: i am hesitant to make it protected as in the future I will be making it private again once i finish the validation.  I have quite a bit of work done towards that end and should be able to finish it up this weekend.

Does that sound good?  I don't foresee any major roadblocks that would prevent me from finishing it.

**Comment by dcarbone** [comment]
@shehi: i have just released v2.0.4 with basic validation implemented.

**Comment by shehi** [comment]
Works fine. Thanks a lot!
