### ISSUE TITLE
0.5.x might be missing a file

### ISSUE THREAD

**Issue by tbitowner** [dcarbone/php-fhir#59]
Using tag 0.5.2 now, which includes file https://github.com/dcarbone/php-fhir/blob/0.5.2/src/ClassGenerator/Config.php. The dev branch, 0.5.x, seems to be missing this file.

**Comment by dcarbone** [comment]
@tbitowner yeah the 0.5.x branch hadn't been used in ages, i did the final amount of 0.5 work in master.

I have merged all of 0.5.2 into 0.5.x branch.  i won't be doing any more active development on that version.

**Comment by hendeavors** [comment]
Thanks @dcarbone  . Meant to post the original as this account 😞. This gives me a starting point to upgrade my own libraries dependent on this project. Excellent work.
