### ISSUE TITLE
Xmlns not filled

### ISSUE THREAD

**Issue by leonrenkema** [dcarbone/php-fhir#63]
Thanks for the quick replies on the pull requests!

We also had to revert this change (https://github.com/dcarbone/php-fhir/commit/9d5d58b37ab3cb750d952c9f03ba438fb4ec230a#diff-19e00af0788a0bd19f34a533b75b49e1L81) because the xmlns of the root element remains empty.

**Comment by dcarbone** [comment]
Yeah, the current state of master is halfway between a fairly large update that aims to achieve output that would be (closer to) passing the upstream validator.

I've had to get over certain opinions of mine, such as that object fields must be alphabetized for easier scanning and a few other things, but ultimately it'll make for a better lib so w/e, lol.

All that to say, it'll be a bit in flux for awhile, possibly the next few months, so apologies for that.

**Comment by dcarbone** [comment]
@leonrenkema: Sorry for the massive delay, but this is addressed in v3!  Hope to have a release cut tomorrow :)

**Comment by leonrenkema** [comment]
Thanks anyway, I will give the release a testrun.
