### ISSUE TITLE
Get nodes details from FHIR after parsing 

### ISSUE THREAD

**Issue by SobhieSaad** [dcarbone/php-fhir#66]
Hi there,
Is there a way to reach "Patient" node without convetting the response to json with json_encode in PHP after :
$parser->parse($input) ;
I got PHPFhirResponse interface abd I need to reach the patient node without json encode.

**Comment by dcarbone** [comment]
@SobhieSaad: I'm not sure I understand the problem here.  If you need to get to a child object, you'll need to use the relevant getter methods to traverse the tree to get to the object you want.

Could you provide a code sample that illustrates what you're trying to do?

**Comment by SobhieSaad** [comment]
@dcarbone no problem I found it. Thank you and will close the issue. Yes it is using getters.
