### ISSUE TITLE
_assertMaxLength reports an error for values lower than max length.

### ISSUE THREAD

**Issue by jnederhof** [dcarbone/php-fhir#67]
_assertMaxLength in phpfhir_validation_assertions.php reports an error for values lower then max length.

`"Field \"value\" on type \"id-primitive\" must be no more than 64 characters long, 1 seen"`

**Comment by dcarbone** [comment]
@jnederhof: yep, got my signs backwards. i'll get a fix pushed tonight.

**Comment by jnederhof** [comment]
Great. Any chance you can push it this week?

**Comment by dcarbone** [comment]
@jnederhof give v2.0.6 a try please.

**Comment by jnederhof** [comment]
> @jnederhof give v2.0.6 a try please.

Thanks. It works as intended!
