### ISSUE TITLE
The id property is always added as a child element instead of an attribute

### ISSUE THREAD

**Issue by 0xPr0xy** [dcarbone/php-fhir#7]
In MethodGenerator.php implementXMLSerialize() method,
The id property is always added as a new child element. I think this is incorrect behavious.
Looking at the fhir spec the id of an element is always specified as an attribute of that element.

It could be solved by doing a check on the property value, and in case of an id, add it as attribute.

**Comment by dcarbone** [comment]
@0xPr0xy: I'm not entirely certain that is correct.  An ID Element is technically an extension of the base Element class.  This means that it can contain Extension elements, and an ID primitive element of it's own aside from it's "value".

The ID Element does have an ID primitive that is represented as an attribute on the exported ID element, but the ID element itself is not a primitive and as a result must be exported as it's own distinct element, as such:

```xml
<id value="primitive-value">
    <extension>blahblah</extension>
    <extension>blah</extension>
</id>
```

This is made more complicated in JSON, which I still have yet to really flesh out, as it is represented as such:

```json
"id": "primitive-value",
"_id": {
    "extension": [{"blahblah"}, {"blah"}],
}
```

The "blahblah" components are obviously not correct, but I hope it illustrates the point.

To be honest, I am only basing this off of what I have seen from the server implementations done by Graham, one of the originators of the FHIR specification.  If you can provide a link to a server which does it differently I can certainly attempt to accommodate both, possibly with a config flag of some sort.

**Comment by 0xPr0xy** [comment]
@dcarbone I understand you reasoning, and looking at the fhir spec I see this behaviour is correct. However I am unclear as to how I can achieve the following result using your bundle: (example xml message for the koppeltaal server based on fhir) https://gist.github.com/0xPr0xy/8c823bb71db4c281e696facfa9e69e3f, (note the id attribute of the MessageHeader and CarePlan.) Perhaps I should create a fork of this bundle to make it specific for the extension on fhir by koppeltaal, or do you think we can support both specs in this bundle?

**Comment by dcarbone** [comment]
Hmm. Well it should be fine if I updated it to do both, or perhaps create a config array that gets passed in to the `parse` method of the generator that has a key like `xml-export => [id-as-attribute => true]`, or something like that. 

Do you have examples of other primitive wrapper elements that are turned into attributes or is ID the only one?

**Comment by dcarbone** [comment]
@0xPr0xy: I'm going to re-open this as you bring up a valid point, and I believe this lib should be made to accommodate situations like yours as much as possible.

I have a few other things in the pipeline before I can being addressing this, but I do want to keep it in mind.

**Comment by dcarbone** [comment]
Closing as this functionality was handled thanks to @0xPr0xy in #15!
