### ISSUE TITLE
Issue running

### ISSUE THREAD

**Issue by Jxckaroo** [dcarbone/php-fhir#76]
Hello!

I am having a few issues trying to get this running & I think it might be because one of your dependencies requires PHP8?

```php
// next, build definition class
$definition = new \DCarbone\PHPFHIR\Definition($config);
```

Parameter #1 expects type VersionConfig.

Am I missing something? :)

**Comment by dcarbone** [comment]
@Jxckaroo hmm, yes apologies looks like I haven't properly updated the README in quite some time!  I'll get a fix pushed asap :)
