### ISSUE TITLE
fhir_comments not supported on Meta element

### ISSUE THREAD

**Issue by kchapple** [dcarbone/php-fhir#8]
Here is message form exception: "Could not find mapped property called "fhir_comments" on object "Meta".  This could indicate malformed response or bug in class generator."

**Comment by dcarbone** [comment]
@kchapple: Hey Ken,

What version of FHIR are you using when you encounter this error?

**Comment by kchapple** [comment]
I am using dev-master. Here's my composer.json:
...
    "repositories":
    [
      {
      "type": "vcs",
      "url": "https://github.com/dcarbone/php-fhir.git"
    }
    ],
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "jeroen-g/laravel-packager": "^1.3",
        "dcarbone/php-fhir": "dev-master"
    },
...

**Comment by dcarbone** [comment]
No, sorry, the FHIR spec.  DSTU2?

**Comment by kchapple** [comment]
Version is 2.6. Here is my Gen script:
```

require __DIR__.'/../../../../vendor/autoload.php';
$xsdPath = __DIR__.'/../schemas/fhir-codegen-xsd-2.6';
$outputPath = __DIR__.'/../src';
$generator = new \DCarbone\PHPFHIR\ClassGenerator\Generator( $xsdPath, $outputPath );
$generator->generate();
```

FYI, this is not a blocker or anything, just thought I'd let you know.

**Comment by dcarbone** [comment]
Hmm alright, looking at the actual definition of the Meta element (line 3910 in "fhir-base.xsd") I do not see a "fhir_comment" element.

This is actually a good use case of an issue I've been thinking about for awhile: How to handle server responses which vary from the spec.  Technically speaking in most cases these differences are probably benign, with the only real downside being I cannot specifically account for them beforehand and thus would make it difficult to efficiently parse and generate XML / JSON.

I've been thinking of implementing something like an `_extra` property, which is simply an array of additional properties seen on a given object that were not seen in the spec.  This could then be pretty easily populated during parsing and converted to JSON / XML during exporting.

Would something like that work for you?

**Comment by kchapple** [comment]
That's funny, I got the sample request from their documentation pages. I wonder why it's not in the schema definition.

For Example:
https://www.hl7.org/fhir/bundle-transaction.json.html

**Comment by kchapple** [comment]
There is support for extensions: 

Here's an example patient with extensions for compliance statement checkboxes:

```
{
        "resourceType": "Patient",
        "name": [
          {
            "text": "Judy Everywoman3",
            "family": [
              "Everywoman3"
            ],
            "given": [
              "Judy Simple"
            ]
          }
        ],
        "gender": "female",
        "birthDate": "1955-01-06",
        "telecom": [
          {
            "system": "phone",
            "value": "555-555-2003",
            "use": "primary"
          },
          {
            "system": "email",
            "value": "ken@mi-squared.com",
            "use": "primary"
          }
        ],
        "photo": [
          {
            "contentType": "image/jpeg",
            "data": "R0lGODlhEwARAPcAAAAAAAAA/+9aAO+1AP/WAP/eAP/eCP/eEP/eGP/nAP/nCP/nEP/nIf/nKf/nUv/nWv/vAP/vCP/vEP/vGP/vIf/vKf/vMf/vOf/vWv/vY//va//vjP/3c//3lP/3nP//tf//vf///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////yH5BAEAAAEALAAAAAATABEAAAi+AAMIDDCgYMGBCBMSvMCQ4QCFCQcwDBGCA4cLDyEGECDxAoAQHjxwyKhQAMeGIUOSJJjRpIAGDS5wCDly4AALFlYOgHlBwwOSNydM0AmzwYGjBi8IHWoTgQYORg8QIGDAwAKhESI8HIDgwQaRDI1WXXAhK9MBBzZ8/XDxQoUFZC9IiCBh6wEHGz6IbNuwQoSpWxEgyLCXL8O/gAnylNlW6AUEBRIL7Og3KwQIiCXb9HsZQoIEUzUjNEiaNMKAAAA7"
          }
        ],
        "extension": [
          {
            "extension": [
              {
                "url": "#terms-of-service",
                "valueBoolean": 1
              },
              {
                "url": "#allow-sms",
                "valueBoolean": 1
              }
            ],
            "url": "https://fhirdev.ttdnow.com/extension/contracts"
          }
        ]
      }
```

**Comment by dcarbone** [comment]
Sure sure, however the "fhir_comment" property does not follow the extension model. It is seemingly defined as a root property on all objects, extension or otherwise.

With that in mind, however, I can pretty easily account for this.  I need to do additional work on the JSON parsing / exporting anyway, so this is a good opportunity to just go ahead and do it.

**Comment by kchapple** [comment]
Yeah, in the examples they seem to just stick the fhir_comment property anywhere, LOL. Sometimes it's in a sibling element, sometimes at the root. I wonder if it is just intended for documenting the examples, and should be ignored entirely by your parser.

**Comment by dcarbone** [comment]
@kchapple I know its been ages, but I have finally finished the initial implementation for this feature.  Could you give v1.0.5 a try and see if it is sufficient?

**Comment by dcarbone** [comment]
Closing this issue as `"fhir_comment"` json entries are now handled.
