### ISSUE TITLE
Confused about how to work with this spec

### ISSUE THREAD

**Issue by mbuk** [dcarbone/php-fhir#88]
Hi folks

Can someone point me in the right direction? The FHIR spec I'm working with states:

```
"FHIR R4 (v4.0.1)] except does not support the http://hl7.org/fhir/R4/http.html#capabilities interaction.
It includes some country-specific FHIR extensions, which are built against UKcore.stu1 0.5"
```

Just a bit confused.

**Comment by mbuk** [comment]
Hey thanks for the quick reply. In relation to the generator library 👍

**Comment by dcarbone** [comment]
Hmm, ok, so what is the issue you're running into?  Where are you receiving this message from?

**Comment by mbuk** [comment]
The bit I'm stuck on is getting the correct config so I can generate the classes. The spec comes from [here](https://digital.nhs.uk/developer/api-catalogue/electronic-prescription-service-fhir#overview--technology)

The R4 part I'm clear on - it's the UKcore.stu1 0.5.1 bit I'm not sure on.

Feel like I've got a blind spot on this and I'm missing something really basic.  Sorry!

**Comment by dcarbone** [comment]
So what happens when you attempt to utilize the generated R4 code against their API?

**Comment by mbuk** [comment]
So - I've just been through step by step and I'm getting the expected results.
I think I must have mixed up the version or the config when I was setting this up originally and got my self confused. 
It's working as I'd expect now - eg: I can get  patient name

Sorry to clearly I was doing something wrong before and I couldn't see it but walking through it again I've clearly corrected the mistake.
