### ISSUE TITLE
Not Converting Fhir Object to XML String

### ISSUE THREAD

**Issue by vikaspal10297** [dcarbone/php-fhir#89]
Hi All,

I hope this message finds you well.

I am relatively new to FHIR and currently working on a project where I am utilizing this repository. However, I've encountered an issue while attempting to convert a FHIR object into an XML string.

I've scrutinized my code, but I'm unsure whether the problem lies there or if it's an issue with the repository itself. I was wondering if anyone here has experience with this and could provide some guidance.

For context, I've included a snippet of my code below:

```
require __DIR__ . '../../../vendor/autoload.php';

$config = new PHPFHIRResponseParserConfig([
'registerAutoloader' => true,
'sxeArgs' => LIBXML_COMPACT | LIBXML_NSCLEAN
]);

$parser = new PHPFHIRResponseParser($config);

$object = $parser->parse($dData);	

$element = $object->xmlSerialize();

$xmlString = $element->asXML();

echo "<pre>";print_r($xmlString);die;
```
but i am getting the fhir object and values in this $element

**Comment by kingpfogel** [comment]
> encountered an issue while attempting to convert a FHIR object into an XML string.

As far as I understood from the README.md on the $object you have to call:
`$xmlString = $object->xmlSerialize()->ownerDocument->saveXML();`
in order to get the XML string.

**Comment by dcarbone** [comment]
I will make testing and updating docs a specific part of the v3 milestone

**Comment by dcarbone** [comment]
@vikaspal10297: I have updated the documentation to properly describe how to get an XML string with v3.0.0
