### ISSUE TITLE
UnexpectedValueException: Value 'integer64' is not part of the enum DCarbone\PHPFHIR\Enum\PrimitiveTypeEnum

### ISSUE THREAD

**Issue by HTech37** [dcarbone/php-fhir#91]
Hello @dcarbone,

Thank you for the useful library. As a beginner in handling fhir format, I find it a boon. I have stored the XSD files in input folder.
 I am getting this error while trying to get the classes. I have attached the screenshot too. Please help me through your guidance. PHP version8.1

![enumerror](https://github.com/dcarbone/php-fhir/assets/152364919/b73a3db5-0099-4da6-a2c3-3318e04d1b5b)

Printing $version_config and $definition
![print](https://github.com/dcarbone/php-fhir/assets/152364919/1d59ea63-1af8-4517-9bed-55b2fd5618bc)

**Comment by dcarbone** [comment]
@HTech37: I have release v3.0.0 with R5 support, let me know if it works for you!
